@if ($tsContentData)

    @foreach ($tsContentData as $content)
        @if ($content->layout == 'hero_slider')
            @include('partials.sections.hero_slider')
        @elseif ($content->layout == 'image_with_content')
            @include('partials.sections.image_with_content')
        @elseif ($content->layout == 'featured_service')
            @include('partials.sections.featured_service')
        @elseif ($content->layout == 'background_image_with_content')
            @include('partials.sections.background_image_with_content')
        @elseif ($content->layout == 'ratings_and_reviews')
            @include('partials.sections.ratings_and_reviews')
        @elseif ($content->layout == 'content_banner')
            @include('partials.sections.content_banner')
        @elseif ($content->layout == 'full_video_section')
            @include('partials.sections.full_video_section')
        @elseif ($content->layout == 'simple_content')
            @include('partials.sections.simple_content')
        @elseif ($content->layout == 'our_doctors_listing')
            @include('partials.sections.our_doctors_listing')
        @elseif ($content->layout == 'video_grid')
            @include('partials.sections.video_grid')
        @elseif ($content->layout == 'list_content')
            @include('partials.sections.list_content')
        @elseif ($content->layout == 'content_with_full_image')
            @include('partials.sections.content_with_full_image')
        @elseif ($content->layout == 'cta_section')
            @include('partials.sections.cta_section')
        @elseif ($content->layout == 'our_procedures_listing')
            @include('partials.sections.our_procedures_listing')
        @elseif ($content->layout == 'patient_reviews_listing')
            @include('partials.sections.patient_reviews_listing')
        @elseif ($content->layout == 'instructions_listing')
            @include('partials.sections.instructions_listing')
        @elseif ($content->layout == 'contact_info')
            @include('partials.sections.contact_info')
        @elseif ($content->layout == 'map_section')
            @include('partials.sections.map_section')
        @elseif ($content->layout == 'contact_form')
            @include('partials.sections.contact_form')
        @elseif ($content->layout == 'community_listing')
            @include('partials.sections.community_listing')
        @elseif ($content->layout == 'information_listing')
            @include('partials.sections.information_listing')
        @elseif ($content->layout == 'general_content')
            @include('partials.sections.general_content')
        @elseif ($content->layout == 'blog_listing')
            @include('partials.sections.blog_listing')
        @endif
    @endforeach
@else
@endif
